# -*- coding: utf-8 -*-
# Generated by Django 1.11.9 on 2018-01-23 09:02
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Toutiao',
            fields=[
                ('id', models.CharField(max_length=254, primary_key=True, serialize=False, verbose_name='编号')),
                ('image_url', models.URLField(null=True, verbose_name='图片地址')),
                ('title', models.TextField(verbose_name='标题')),
                ('media_creator_id', models.CharField(max_length=254, verbose_name='作者编号')),
                ('media_name', models.TextField(verbose_name='作者昵称')),
            ],
        ),
    ]
